# Is it a view or a copy?

- For every operations on the array `x`, decide whether it returns a view of `x`, or a copy
- If it's a view, derive the new values for the metadata (ndim, shape, strides)
- You can verify your answers with the function `print_info` defined below

In [1]:
import numpy as np


def is_view(a, x):
    """ Is `a` a view of `x`? """
    return a.base is x


def print_info(a, x):
    txt = f"""
Is it a view? {is_view(a, x)}

dtype\t{a.dtype}
ndim\t{a.ndim}
shape\t{a.shape}
strides\t{a.strides}
    """
    print(a)
    print(txt)


x = np.arange(12).reshape(3, 4).copy()
print_info(x, x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Is it a view? False

dtype	int64
ndim	2
shape	(3, 4)
strides	(32, 8)
    


In [2]:
y = x[::2, :]
#print_info(y, x)

In [3]:
y = x[1, :]
#print_info(y, x)

In [5]:
y = x[[1, 2, 0], [1, 1, 2]]
print_info(y, x)

[5 9 2]

Is it a view? False

dtype	int64
ndim	1
shape	(3,)
strides	(8,)
    


In [6]:
# Get the first and third row
y = x[[0, 2], :]
#print_info(y, x)

In [7]:
y = x.reshape((6, 2))
#print_info(y, x)

In [8]:
y = x.ravel()
#print_info(y, x)

In [9]:
y = x.T.ravel()
#print_info(y, x)

In [10]:
# Get all the odd elements
y = x[(x % 2) == 1]
#print_info(y, x)