# Is it a view or a copy?


In [14]:
import numpy as np


def is_view(a, x):
    """ Is `a` a view of `x`? """
    return a.base is x


def print_info(a, x):
    txt = f"""
Is it a view? {is_view(a, x)}

dtype\t{a.dtype}
ndim\t{a.ndim}
shape\t{a.shape}
strides\t{a.strides}
    """
    print(txt)


In [15]:
x = np.arange(12).reshape(3, 4).copy()
print(x)
print_info(x, x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Is it a view? False

dtype	int64
ndim	2
shape	(3, 4)
strides	(32, 8)
    


In [3]:
y = x[::2, :]
print(y)

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
print_info(y, x)

In [5]:
y = x[1, :]
print(y)

[4 5 6 7]


In [ ]:
print_info(y, x)

In [6]:
y = x[[1, 2, 0], [1, 1, 2]]
print(y)

[5 9 2]


In [ ]:
print_info(y, x)

In [7]:
# Get the first and third row
y = x[[0, 2], :]
print(y)

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
print_info(y, x)

In [8]:
y = x.reshape((6, 2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
print_info(y, x)

In [9]:
y = x.ravel()
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print_info(y, x)

In [10]:
y = x.T.ravel()
print(y)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [ ]:
print_info(y, x)

In [11]:
# Get all the odd elements
y = x[(x % 2) == 1]
print(y)

[ 1  3  5  7  9 11]


In [ ]:
print_info(y, x)