In [3]:
import numpy as np

In [4]:
x = np.arange(12).reshape(4,3)

In [5]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
y = x.T

In [7]:
y

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [8]:
y[0, 0] = 13

In [9]:
y

array([[13,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [10]:
x

array([[13,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])