In [1]:
import numpy as np

In [2]:
def robust_log(x, cte=1e-10):
    """ Compute the log of the elements of an array.
    
    Values that are equal to 0.0 in `x` are substituted with a tiny constant `cte`
    to avoid a divide-by-zero warning, and `-inf` values in the output arrays.
    """
    x[x == 0] = cte
    return np.log(x)


In [3]:
a = np.array([[0.3, 0.01], [0, 1]])
print(a)

[[0.3  0.01]
 [0.   1.  ]]


In [4]:
# Using the NumPy's log directly
np.log(a)

/tmp/ipykernel_50294/3282750587.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[-1.2039728 , -4.60517019],
       [       -inf,  0.        ]])

In [5]:
# Our function handles values equal zero to return a small value
robust_log(a)

array([[ -1.2039728 ,  -4.60517019],
       [-23.02585093,   0.        ]])

In [6]:
a = np.array([[0.3, 0.01], [0, 1]])
b = a[1, :]  # A view of `a`
print(b)

[0. 1.]


In [7]:
robust_log(b)

array([-23.02585093,   0.        ])

In [8]:
b

array([1.e-10, 1.e+00])

In [9]:
a

array([[3.e-01, 1.e-02],
       [1.e-10, 1.e+00]])

Functions that take an array as an input should **avoid modifying it in place!**

Always make a copy or be super extra clear in the docstring.

In [ ]:
def robust_log(x, cte=1e-10):
    """ Compute the log of the elements of an array.
    
    Values that are equal to 0.0 in `x` are substituted with a tiny constant `cte`
    to avoid a divide-by-zero warning, and `-inf` values in the output arrays.
    """
    x = x.copy()
    x[x == 0] = cte
    return np.log(x)